version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - "npm install -g gatsby"
  build:
    commands:
      - "npm run-script build"
artifacts:
  base-directory: public
  files:
    - "**/*"
  discard-paths: no
cache:
  paths:
    - ".cache/*"
    - "public/*"